### ISSUE TITLE
Mobs Pathfinding with Bridge

### ISSUE THREAD

**Issue by ardissaps** [sketchmacaw/MacawsModsIssues#200] opened 2022-06-13 04:20 UTC
Thanks for the great mod

**Describe the bug**
Mob that follow player does not follow trough bridge

**Mod name & Minecraft Version and Modloader**
Macaw Bridge, MCA, Vanilla

**To Reproduce**
1. Go to mob that can follow us
2. Pass bridge
3. Mob can not pass bridge

**Comment by sketchmacaw** [comment] 2022-06-13 11:52
duplicate of [[Issue#6]](https://github.com/sketchmacaw/MacawsModsIssues/issues/6)

**Comment by ardissaps** [comment] 2022-06-14 13:54
Slab also work, which look a more aesthetic, for now :D

**Comment by sketchmacaw** [comment] 2024-04-06 13:29
Fixed in upcoming 3.0.0 update

**Closed by sketchmacaw** 2024-04-06 13:29 UTC
Labels: duplicate, suggestion, Macaw's Bridges
