### ISSUE TITLE
Lower roof cannot be places if it has a block behind it + idea for better lower roof

### ISSUE THREAD

**Issue by winsrp** [sketchmacaw/MacawsModsIssues#32] opened 2020-08-16 05:14 UTC
So I'm doing a very large build (in survival with my gf, crazy I know!, the survival part not the gf part XD), and using lowered roof since the roof spans a big area, and should not go that high. If while trying to place the lowered roof it has a block behind it, the game wont allow me to place the lowered roof block, I need to remove the block behind first, then place the roof and then place the block back behind the roof... quite a pain.... 

Another issue was making corners with this.... that is simply not possible, so I had a suggestion, why not have the lowered roof split in its 2 parts, lowered roof bottom, and lowered roof top, and have them work in corners like normal roof does?, this would allow for a more dynamic use of both parts, since this is the equivalent of slab + block + slab + etc... 

Labels: 1.16, Macaw's Roofs, suggestion, bug

**Comment by Arcitect-X** [comment] 2021-02-21 01:31
I can confirm that you can not place a lower roof if there is a block behind it

**Comment by DHWise** [comment] 2021-03-05 12:16
Also the hammer as no effect on the lower roof block.

**Comment by Wishbone1977** [comment] 2021-03-14 17:11
> I can confirm that you can not place a lower roof if there is a block behind it. 1.16.5

Another confirmation. 1.16.5-4.

Also, I seem to only be able to place the lower roof sideways. In other words, if I place it on a block in front of me, it will place with the taller bit on that block, and the lower bit on the block to the right of it. The normal roofs place as I would expect, sloping down towards me when I place them in front of me.

Additionally, I cannot place lower roofs on the side of other lower roofs (for extending a roof sideways) which basically makes them useless.

**Comment by sketchmacaw** [comment] 2021-03-14 17:15
The lower roof will be split into 2 pieces, it is a great idea an it would allow to build roofs with more possibilities. Also with splitting them into two pieces they would have cornering. This issue would be fixed too.

**Comment by Wishbone1977** [comment] 2021-03-14 18:12
> The lower roof will be split into 2 pieces, it is a great idea an it would allow to build roofs with more possibilities. Also with splitting them into two pieces they would have cornering. This issue would be fixed too.

Sounds awesome. Looking forward to it :-)

**Comment by winsrp** [comment] 2021-04-08 16:51
sounds great, can't wait for the update.

**Comment by xXNickznXx** [comment] 2021-12-13 23:35
Wouldnt it be easier to make a half-block high roof and that is acts like a slab? Then you dont need 2 parts for it.
Slab placement: https://minecraft.fandom.com/wiki/Slab#Placement

**Comment by sketchmacaw** [comment] 2021-12-14 00:06
Interesting idea, but I feel like it could be frustrating to pay so much attention when placing them. In the last days I've been thinking of having a tool which would swap between the states.

**Comment by xXNickznXx** [comment] 2021-12-19 01:56
I dont really like the idea of a tool to swap trough blockstates, the more states the more annoying it gets. When it would work like a slab, it would be much more minecraft like. There are several blocks in vanilla with this placement style: Slabs, Stairs, Trapdoors and probably more.

**Comment by sketchmacaw** [comment] 2021-12-19 02:45
But without placing a block behind it first there is no way to define if they want it to be a tall roof. I think I'm just going to make a vote on my discord server. Again your way would be a lot easier to make it work code wise.

**Comment by sketchmacaw** [comment] 2021-12-28 20:25
> I dont really like the idea of a tool to swap trough blockstates, the more states the more annoying it gets. When it would work like a slab, it would be much more minecraft like. There are several blocks in vanilla with this placement style: Slabs, Stairs, Trapdoors and probably more.

Oh and there will be upside down placing which uses this behavior..

**Comment by xXNickznXx** [comment] 2021-12-28 21:23
Through which states would you iterate?

**Comment by sketchmacaw** [comment] 2021-12-28 21:41
Half just like in stairs

**Comment by xXNickznXx** [comment] 2021-12-28 21:49
So just 2 states: "normal" and "upside down". Sounds great, cant wait for the update to try it out!

**Comment by sketchmacaw** [comment] 2021-12-28 21:59
What I mean is that in this new update., there will be added upside down placement which uses the half state.
(because of very high demand from players). 

> Oh and there will be upside down placing which uses this behavior..

**Comment by xXNickznXx** [comment] 2021-12-28 22:41
In my understanding you would have a half-block-high roof, which you can place like a slab and with the tool you can swap between "normal" or "upside down". Wouldnt that be the easiest way?

**Comment by sketchmacaw** [comment] 2022-01-21 18:35
Fixed in 2.1.0 + Added

**Closed by sketchmacaw** 2022-01-21 18:35 UTC
Labels: bug, WORKING ON IT!, suggestion, 1.14.4, 1.15.2, Macaw's Roofs
