### ISSUE TITLE
Game Crashing After Putting Furniture Mod in Mods Folder

### ISSUE THREAD

**Issue by ghost** [sketchmacaw/MacawsModsIssues#192] opened 2022-05-13 05:47 UTC
World won't load in, stays at 0% and then crashes when I force exit. Only happens after I add this mod in. And after taking out builders addition, exline furniture and decorative blocks trying to load the world crashes the game.

**Macaw's Furniture - 1.18.2 - Forge**

**To Reproduce**
1. Install below mods in forge 1.18.2
2. Try to load a previously created world

**Additional context**
other mods + versions
apotheosis - 5.3.5
aquaculture - 2.3.6
architectury - 4.4.60
betteranimalsplus - 11.0.5
bone equipment - 1.0.1
botania - 431
buildersaddition - 20220308a
carryon - 1.17.0.8
curios - 5.0.7.0
decorative blocks - 2.1.0
druidcraft - 0.0.12
echantment descriptions - 10.0.3
exline furniture - 2.05
exotic birds - 1.4.0
falling leaves - 1.3.2
forbidden arcanus - 2.0.0
guard villagers - 1.4.1
jade - 5.1.0
jei - 9.7.0.194
mcw bridges - 2.0.2
mcw furniture - 3.0.0
optifine - HD U H7
patchouli - 67
placebo - 6.4.0
tough as nails - 7.0.0.69
travelers backpack - 7.1.0
valhelsia core - 0.3.1

I figure either I don't have enough memory allocated or something is incompatible but it's not giving me a crash report or anything

**Comment by sketchmacaw** [comment] 2022-05-29 18:24
Have you tried allocating more memory?

**Comment by Nyoom-Monster** [comment] 2022-07-29 04:15
I think I'm having the same issue with Macaw's Furniture crashing my game. I always find at least one of these mods to be the cause of a crash or game error for my packs.

**Comment by sketchmacaw** [comment] 2022-08-03 13:56
Could you please post me the log?

**Comment by Stanlyhalo** [comment] 2022-08-11 21:51
This happens to me too but with the bridges (1.18.2), while loading it just freezes at the end... but if I remove this mod, it loads fine.

**Comment by sketchmacaw** [comment] 2022-08-11 22:08
Send me the log with the mod in the folder

**Comment by sketchmacaw** [comment] 2023-03-03 00:32
Fixed in the upcoming 3.1.0 update

**Closed by sketchmacaw** 2023-03-03 00:32 UTC
Labels: bug, Macaw's Furniture, 1.18, FORGE
